"""Stretch feature 1 — compare semantic-only, BM25-only, and hybrid retrieval.

Writes stretch_hybrid_results.md. Retrieval only, so this needs no API key.

    python compare_retrieval.py
"""

from __future__ import annotations

import sys
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parent
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

from src.eval_questions import EVAL_QUESTIONS, precision_at_k
from src.hybrid import DEFAULT_ALPHA, search
from src.vector_store import DEFAULT_TOP_K

METHODS = ("semantic", "bm25", "hybrid")


def format_precision(value: float | None) -> str:
    return "n/a" if value is None else f"{value:.2f}"


def main() -> None:
    lines: list[str] = [
        "# Hybrid Search Comparison",
        "",
        f"Generated by `python compare_retrieval.py` — top-k = {DEFAULT_TOP_K}, "
        f"hybrid alpha = {DEFAULT_ALPHA}.",
        "",
        "`precision@5` is the fraction of the top 5 chunks coming from a source file",
        "hand-labeled as relevant in `src/eval_questions.py`. Question 5 is out-of-scope,",
        "so no document is relevant and precision is undefined.",
        "",
    ]

    totals: dict[str, list[float]] = {method: [] for method in METHODS}

    for item in EVAL_QUESTIONS:
        lines.append(f"## Question {item.number}")
        lines.append("")
        lines.append(f"`{item.question}`")
        lines.append("")
        if item.relevant_sources:
            lines.append(f"Relevant source files: {', '.join(sorted(item.relevant_sources))}")
        else:
            lines.append("Relevant source files: none — the corpus does not cover this question.")
        lines.append("")

        summary_rows: list[str] = []

        for method in METHODS:
            hits = search(item.question, top_k=DEFAULT_TOP_K, method=method)
            sources = [hit.source_file for hit in hits]
            precision = precision_at_k(sources, item.relevant_sources)
            if precision is not None:
                totals[method].append(precision)

            recall_note = ""
            if item.required_chunk_ids:
                found = {hit.chunk_id for hit in hits} & item.required_chunk_ids
                recall_note = f"{len(found)}/{len(item.required_chunk_ids)}"

            summary_rows.append(
                f"| {method} | {format_precision(precision)} | {recall_note or '—'} | "
                + ", ".join(f"`{hit.source_file}`" for hit in hits)
                + " |"
            )

            lines.append(f"### {method}")
            lines.append("")
            lines.append("| Rank | Chunk ID | Source file | Score |")
            lines.append("|---|---|---|---|")
            for rank, hit in enumerate(hits, start=1):
                score = f"{hit.score:.4f}"
                if method == "hybrid":
                    score += (
                        f" (sem {hit.components['normalized_semantic']:.3f} /"
                        f" bm25 {hit.components['normalized_bm25']:.3f})"
                    )
                lines.append(f"| {rank} | `{hit.chunk_id}` | {hit.source_file} | {score} |")
            lines.append("")

        lines.append("### Comparison")
        lines.append("")
        lines.append("| Method | precision@5 | required chunks found | Retrieved source files |")
        lines.append("|---|---|---|---|")
        lines.extend(summary_rows)
        lines.append("")

    lines.append("## Mean precision@5 across the 4 in-scope questions")
    lines.append("")
    lines.append("| Method | Mean precision@5 |")
    lines.append("|---|---|")
    for method in METHODS:
        scores = totals[method]
        mean = sum(scores) / len(scores) if scores else 0.0
        lines.append(f"| {method} | {mean:.3f} |")
    lines.append("")

    output_path = ROOT_DIR / "stretch_hybrid_results.md"
    output_path.write_text("\n".join(lines), encoding="utf-8")

    for method in METHODS:
        scores = totals[method]
        mean = sum(scores) / len(scores) if scores else 0.0
        print(f"{method:>9}: mean precision@5 = {mean:.3f}")
    print(f"\nWrote {output_path}")


if __name__ == "__main__":
    main()
